ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080

storage:
  driverClassName: "org.postgresql.Driver"
  jdbcUrl: "jdbc:postgresql://localhost:5432/baseSpotifyMusicClon"
  dbUser: "postgres"
  dbPassword: "qwerty123"